osx_image: xcode7.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
env:
  global:
  # GH_TOKEN
  - secure: EpeYT6T82lfJrnQn9QwHDxLRx9iT30yQp8NHIs+rH0T7Yxegm6YRHYr8nLOen/Ny+Kyq9qNeW6D3kelkWsfMADXIQKh7n/vSjXb535+iQeMOUSVQu8PKFzkwDLJIbYKRugVZJ2k+nqsBPqbiG5RiV71ztWgxz4GN28nLnJIYhiCA2yCilITS/WcreHUSAjFUWubQQTCptFHTYTvNKxclw9eps6vwPM0/+KSnbM5SD5O14ZtjairSwj72+RjT3WveAznD2nzqjroKd1r2JZPrRIrQUCj8tKJHilYzWW91IgH9FYJKHjO3VSjv1JiiJrO8LTmur9lArbYBA9pJvbCmg7iXYFUAHMlbKs/yRrIwiMOuKvEX6Mw43YG4zz2X+F5oH1tis8+b1kfehL44gfCNEJtfpJRHEvfafm4WZumar0aZV4xVUYkbYuRj07X/+/kn7Zy9M+obZbVaajh3irCSw79ApSZ0lRciYgVbGE7dHsx6u9CKFKOInONowU2koPkfgTneslmbYpyfRUPQTytYkzfjBFOYj3RFd7ruYr+qdt7ouusKjZmRgO6fNNG8+hYynb/grX8di9sxBSXIuh29EFVNY8uXBVKpyMcJ9AN4TZ/PCMjCfPYxMIyPx9YGE2tTalhuQf1YXT8n72MZGW+7DMWdiGBZzHPZJw2tH9oEtU4=
  # SQLECTRON_SECRET
  - secure: fMCSCBlneTLKfASdqfZ9ZAJoqQhxvEtwOZ1UVDNi+8JqioKamGjP+0vGj9R/t4g667blh8Zc/oXBNNp1g0NKUPFLxv0jBn56fsZW6SZkRhlA2JcKcGCwq6UKWC4fd6leRxy5WaiVCsj2XetfDodPce9RYW8gdpOI6bO/hLGqJCBajfpPJ7bAFSFUSy8NhZ1wiVs6jdFVpyIJ9aRr+kgf0PyuUGL979GT1SOzwi94PrdM97emEPu/fFPutDablvRKHLcTHW4DvVVe8KNH6PHwXmiERcv3u+K7WEuq06omr8C1yYuOQA3oJBzbAc1Qyj3RIIO/u2ovpMokRVDejJ88X/lJ5FqRtTEyAqjOKmEd4eiJNrpY17T34l8ZKxEeFNvWZTzyaXPGVrVNELhqFvyzJspSGeLt9CjQBwxuxwRhtSa5S+/XjdDcszyESdLV81LK7WhY/zh57bV6tuPsFkigLUzECVi136hWNVkKY7F+Wy5/yA6Rrqypt3g7ppwHMrEUWGCPejrewXm14ZPfVMHYR/F/3hXNRa5+99ye348j4MqOhrmA8nN/h/yzT5qhBX1OeUpgGdj5SzGAAI4WLFnptdDjqJn4x/fynZHQXIGQniWk6cISYt0kQ688/Y8TGWz8bKQNDlY3AkJX/l81YJZhRhb/8FL8VyeWZE6KcMV36Ik=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - libgnome-keyring-dev
    - icnsutils
    - clang-3.8
    - graphicsmagick
    - rpm
    - bsdtar
install:
- clang --version
- nvm install 6
- npm prune
- npm install
script:
- npm test
- npm run dist
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
